"""initial schema

Revision ID: eb560e7c7c5c
Revises: 
Create Date: 2026-08-30 03:31:40.207810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb560e7c7c5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_changed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_key', sa.String(length=220), nullable=False),
    sa.Column('company', sa.String(length=220), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=80), nullable=False),
    sa.Column('board', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('filing_date', sa.String(length=20), nullable=False),
    sa.Column('open_date', sa.String(length=20), nullable=False),
    sa.Column('close_date', sa.String(length=20), nullable=False),
    sa.Column('listing_date', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('issue_size_m', sa.Float(), nullable=True),
    sa.Column('shares_offered_m', sa.Float(), nullable=True),
    sa.Column('post_issue_shares_m', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('revenue_m', sa.Float(), nullable=True),
    sa.Column('revenue_prev_m', sa.Float(), nullable=True),
    sa.Column('revenue_2y_ago_m', sa.Float(), nullable=True),
    sa.Column('ebitda_m', sa.Float(), nullable=True),
    sa.Column('net_income_m', sa.Float(), nullable=True),
    sa.Column('cfo_m', sa.Float(), nullable=True),
    sa.Column('debt_m', sa.Float(), nullable=True),
    sa.Column('cash_m', sa.Float(), nullable=True),
    sa.Column('fresh_issue_pct', sa.Float(), nullable=True),
    sa.Column('ofs_pct', sa.Float(), nullable=True),
    sa.Column('promoter_retention_pct', sa.Float(), nullable=True),
    sa.Column('qib_sub', sa.Float(), nullable=True),
    sa.Column('nii_sub', sa.Float(), nullable=True),
    sa.Column('retail_sub', sa.Float(), nullable=True),
    sa.Column('total_sub', sa.Float(), nullable=True),
    sa.Column('gmp_pct', sa.Float(), nullable=True),
    sa.Column('underwriter_quality', sa.Float(), nullable=True),
    sa.Column('anchor_quality', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.Float(), nullable=True),
    sa.Column('sector_regime', sa.Float(), nullable=True),
    sa.Column('dual_class', sa.Boolean(), nullable=True),
    sa.Column('lockup_days', sa.Integer(), nullable=True),
    sa.Column('market_overhang_pct', sa.Float(), nullable=True),
    sa.Column('peer_median_pe', sa.Float(), nullable=True),
    sa.Column('peer_median_ps', sa.Float(), nullable=True),
    sa.Column('peer_median_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('registrar', sa.String(length=160), nullable=False),
    sa.Column('allotment_url', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('data_flags', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipos_company'), 'ipos', ['company'], unique=False)
    op.create_index(op.f('ix_ipos_country'), 'ipos', ['country'], unique=False)
    op.create_index(op.f('ix_ipos_external_key'), 'ipos', ['external_key'], unique=True)
    op.create_index(op.f('ix_ipos_status'), 'ipos', ['status'], unique=False)
    op.create_index(op.f('ix_ipos_symbol'), 'ipos', ['symbol'], unique=False)
    op.create_table('waitlist_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('investor_type', sa.String(length=40), nullable=False),
    sa.Column('markets', sa.String(length=40), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=40), nullable=False),
    sa.Column('referred_by', sa.String(length=40), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppressed_reason', sa.String(length=40), nullable=False),
    sa.Column('alert_score_change', sa.Boolean(), nullable=False),
    sa.Column('alert_recommendation_change', sa.Boolean(), nullable=False),
    sa.Column('alert_red_flag', sa.Boolean(), nullable=False),
    sa.Column('alert_new_ipo', sa.Boolean(), nullable=False),
    sa.Column('digest_weekly', sa.Boolean(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_leads_access_status'), 'waitlist_leads', ['access_status'], unique=False)
    op.create_index(op.f('ix_waitlist_leads_email'), 'waitlist_leads', ['email'], unique=True)
    op.create_index(op.f('ix_waitlist_leads_referral_code'), 'waitlist_leads', ['referral_code'], unique=True)
    op.create_index(op.f('ix_waitlist_leads_unsubscribe_token'), 'waitlist_leads', ['unsubscribe_token'], unique=True)
    op.create_table('worker_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=80), nullable=False),
    sa.Column('current_job', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_sec_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_nse_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_performance_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_email_pass_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['waitlist_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_lead_id'), 'auth_sessions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_session_hash'), 'auth_sessions', ['session_hash'], unique=True)
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['waitlist_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_lead_id'), 'login_tokens', ['lead_id'], unique=False)
    op.create_index(op.f('ix_login_tokens_token_hash'), 'login_tokens', ['token_hash'], unique=True)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.String(length=20), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('listing_return_pct', sa.Float(), nullable=True),
    sa.Column('return_1m_pct', sa.Float(), nullable=True),
    sa.Column('return_6m_pct', sa.Float(), nullable=True),
    sa.Column('return_12m_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_as_of_date'), 'performance_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_ipo_id'), 'performance_snapshots', ['ipo_id'], unique=False)
    op.create_table('provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('observed_value', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_conflict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipo_id', 'field_name', 'source_url', name='uq_provenance')
    )
    op.create_index(op.f('ix_provenance_field_name'), 'provenance', ['field_name'], unique=False)
    op.create_index(op.f('ix_provenance_ipo_id'), 'provenance', ['ipo_id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=False),
    sa.Column('event_stage', sa.String(length=40), nullable=False),
    sa.Column('is_forward', sa.Boolean(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('provenance_ids', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('listing_score', sa.Float(), nullable=False),
    sa.Column('long_term_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('listing_gain_probability', sa.Float(), nullable=False),
    sa.Column('long_term_outperform_probability', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=80), nullable=False),
    sa.Column('horizon', sa.String(length=80), nullable=False),
    sa.Column('valuation_label', sa.String(length=40), nullable=False),
    sa.Column('fair_value_low', sa.Float(), nullable=True),
    sa.Column('fair_value_high', sa.Float(), nullable=True),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('what_changes_verdict', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_created_at'), 'score_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_score_snapshots_event_stage'), 'score_snapshots', ['event_stage'], unique=False)
    op.create_index(op.f('ix_score_snapshots_ipo_id'), 'score_snapshots', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_score_snapshots_is_forward'), 'score_snapshots', ['is_forward'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=True),
    sa.Column('score_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['waitlist_leads.id'], ),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['score_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'template', 'dedupe_key', name='uq_lead_template_dedupe')
    )
    op.create_index(op.f('ix_email_messages_email'), 'email_messages', ['email'], unique=False)
    op.create_index(op.f('ix_email_messages_ipo_id'), 'email_messages', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_email_messages_lead_id'), 'email_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_messages_priority'), 'email_messages', ['priority'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_score_snapshot_id'), 'email_messages', ['score_snapshot_id'], unique=False)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('ix_email_messages_template'), 'email_messages', ['template'], unique=False)
    op.create_table('prediction_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('listing_open_return_pct', sa.Float(), nullable=True),
    sa.Column('listing_close_return_pct', sa.Float(), nullable=True),
    sa.Column('return_7d_pct', sa.Float(), nullable=True),
    sa.Column('return_30d_pct', sa.Float(), nullable=True),
    sa.Column('return_6m_pct', sa.Float(), nullable=True),
    sa.Column('return_12m_pct', sa.Float(), nullable=True),
    sa.Column('return_24m_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_relative_return_pct', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['score_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_snapshot_id', name='uq_outcome_snapshot')
    )
    op.create_index(op.f('ix_prediction_outcomes_ipo_id'), 'prediction_outcomes', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_prediction_outcomes_score_snapshot_id'), 'prediction_outcomes', ['score_snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_outcomes_score_snapshot_id'), table_name='prediction_outcomes')
    op.drop_index(op.f('ix_prediction_outcomes_ipo_id'), table_name='prediction_outcomes')
    op.drop_table('prediction_outcomes')
    op.drop_index(op.f('ix_email_messages_template'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_score_snapshot_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_priority'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_lead_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_ipo_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_email'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_score_snapshots_is_forward'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_ipo_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_event_stage'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_created_at'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_provenance_ipo_id'), table_name='provenance')
    op.drop_index(op.f('ix_provenance_field_name'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_index(op.f('ix_performance_snapshots_ipo_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_as_of_date'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_login_tokens_token_hash'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_lead_id'), table_name='login_tokens')
    op.drop_table('login_tokens')
    op.drop_index(op.f('ix_auth_sessions_session_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_lead_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('worker_heartbeat')
    op.drop_index(op.f('ix_waitlist_leads_unsubscribe_token'), table_name='waitlist_leads')
    op.drop_index(op.f('ix_waitlist_leads_referral_code'), table_name='waitlist_leads')
    op.drop_index(op.f('ix_waitlist_leads_email'), table_name='waitlist_leads')
    op.drop_index(op.f('ix_waitlist_leads_access_status'), table_name='waitlist_leads')
    op.drop_table('waitlist_leads')
    op.drop_index(op.f('ix_ipos_symbol'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_status'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_external_key'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_country'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_company'), table_name='ipos')
    op.drop_table('ipos')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
