from __future__ import annotations
from datetime import datetime, timezone
from sqlalchemy import String, Float, Integer, DateTime, Boolean, Text, ForeignKey, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON
from .db import Base

def utcnow():
    return datetime.now(timezone.utc)

class WaitlistLead(Base):
    __tablename__ = "waitlist_leads"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(160), default="")
    investor_type: Mapped[str] = mapped_column(String(40), default="retail")
    markets: Mapped[str] = mapped_column(String(40), default="both")
    consent: Mapped[bool] = mapped_column(Boolean, default=True)
    referral_code: Mapped[str] = mapped_column(String(40), unique=True, index=True)
    referred_by: Mapped[str] = mapped_column(String(40), default="")
    unsubscribe_token: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    source: Mapped[str] = mapped_column(String(80), default="direct")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

class IPO(Base):
    __tablename__ = "ipos"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_key: Mapped[str] = mapped_column(String(220), unique=True, index=True)
    company: Mapped[str] = mapped_column(String(220), index=True)
    symbol: Mapped[str] = mapped_column(String(32), default="", index=True)
    country: Mapped[str] = mapped_column(String(32), index=True)
    exchange: Mapped[str] = mapped_column(String(80), default="")
    board: Mapped[str] = mapped_column(String(40), default="Mainboard")
    sector: Mapped[str] = mapped_column(String(120), default="Unknown")
    status: Mapped[str] = mapped_column(String(40), default="Filed", index=True)
    filing_date: Mapped[str] = mapped_column(String(20), default="")
    open_date: Mapped[str] = mapped_column(String(20), default="")
    close_date: Mapped[str] = mapped_column(String(20), default="")
    listing_date: Mapped[str] = mapped_column(String(20), default="")
    currency: Mapped[str] = mapped_column(String(8), default="USD")
    price_low: Mapped[float | None] = mapped_column(Float, nullable=True)
    price_high: Mapped[float | None] = mapped_column(Float, nullable=True)
    final_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    issue_size_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    shares_offered_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    post_issue_shares_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    lot_size: Mapped[int | None] = mapped_column(Integer, nullable=True)
    revenue_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    revenue_prev_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    revenue_2y_ago_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebitda_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_income_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    cfo_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    debt_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    fresh_issue_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    ofs_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    promoter_retention_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    qib_sub: Mapped[float | None] = mapped_column(Float, nullable=True)
    nii_sub: Mapped[float | None] = mapped_column(Float, nullable=True)
    retail_sub: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_sub: Mapped[float | None] = mapped_column(Float, nullable=True)
    gmp_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    underwriter_quality: Mapped[float | None] = mapped_column(Float, nullable=True)
    anchor_quality: Mapped[float | None] = mapped_column(Float, nullable=True)
    market_regime: Mapped[float | None] = mapped_column(Float, nullable=True)
    sector_regime: Mapped[float | None] = mapped_column(Float, nullable=True)
    dual_class: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    lockup_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    market_overhang_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    peer_median_pe: Mapped[float | None] = mapped_column(Float, nullable=True)
    peer_median_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    peer_median_ev_ebitda: Mapped[float | None] = mapped_column(Float, nullable=True)
    filing_url: Mapped[str] = mapped_column(Text, default="")
    registrar: Mapped[str] = mapped_column(String(160), default="")
    allotment_url: Mapped[str] = mapped_column(Text, default="")
    raw: Mapped[dict] = mapped_column(JSON, default=dict)
    data_flags: Mapped[list] = mapped_column(JSON, default=list)
    first_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    scores: Mapped[list["ScoreSnapshot"]] = relationship(back_populates="ipo", cascade="all, delete-orphan")
    provenance: Mapped[list["Provenance"]] = relationship(back_populates="ipo", cascade="all, delete-orphan")

class ScoreSnapshot(Base):
    __tablename__ = "score_snapshots"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    ipo_id: Mapped[int] = mapped_column(ForeignKey("ipos.id"), index=True)
    model_version: Mapped[str] = mapped_column(String(40), default="v2.0")
    overall_score: Mapped[float] = mapped_column(Float)
    listing_score: Mapped[float] = mapped_column(Float)
    long_term_score: Mapped[float] = mapped_column(Float)
    confidence: Mapped[float] = mapped_column(Float)
    listing_gain_probability: Mapped[float] = mapped_column(Float)
    long_term_outperform_probability: Mapped[float] = mapped_column(Float)
    recommendation: Mapped[str] = mapped_column(String(80))
    horizon: Mapped[str] = mapped_column(String(80))
    valuation_label: Mapped[str] = mapped_column(String(40))
    fair_value_low: Mapped[float | None] = mapped_column(Float, nullable=True)
    fair_value_high: Mapped[float | None] = mapped_column(Float, nullable=True)
    pillars: Mapped[dict] = mapped_column(JSON, default=dict)
    rationale: Mapped[list] = mapped_column(JSON, default=list)
    risks: Mapped[list] = mapped_column(JSON, default=list)
    what_changes_verdict: Mapped[list] = mapped_column(JSON, default=list)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, index=True)
    ipo: Mapped[IPO] = relationship(back_populates="scores")

class Provenance(Base):
    __tablename__ = "provenance"
    __table_args__ = (UniqueConstraint("ipo_id", "field_name", "source_url", name="uq_provenance"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    ipo_id: Mapped[int] = mapped_column(ForeignKey("ipos.id"), index=True)
    field_name: Mapped[str] = mapped_column(String(100), index=True)
    source_name: Mapped[str] = mapped_column(String(100))
    source_url: Mapped[str] = mapped_column(Text, default="")
    source_tier: Mapped[int] = mapped_column(Integer, default=2)
    observed_value: Mapped[str] = mapped_column(Text, default="")
    observed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    is_conflict: Mapped[bool] = mapped_column(Boolean, default=False)
    ipo: Mapped[IPO] = relationship(back_populates="provenance")

class PerformanceSnapshot(Base):
    __tablename__ = "performance_snapshots"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    ipo_id: Mapped[int] = mapped_column(ForeignKey("ipos.id"), index=True)
    as_of_date: Mapped[str] = mapped_column(String(20), index=True)
    close_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    listing_return_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_1m_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_6m_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_12m_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    benchmark_return_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    source_name: Mapped[str] = mapped_column(String(100), default="")
    source_url: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

class IngestionRun(Base):
    __tablename__ = "ingestion_runs"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    source: Mapped[str] = mapped_column(String(100), index=True)
    status: Mapped[str] = mapped_column(String(30), default="running")
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rows_seen: Mapped[int] = mapped_column(Integer, default=0)
    rows_changed: Mapped[int] = mapped_column(Integer, default=0)
    error: Mapped[str] = mapped_column(Text, default="")
    metadata_json: Mapped[dict] = mapped_column(JSON, default=dict)

class NotificationLog(Base):
    __tablename__ = "notification_logs"
    __table_args__ = (UniqueConstraint("lead_id", "score_snapshot_id", name="uq_lead_score_alert"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    lead_id: Mapped[int] = mapped_column(ForeignKey("waitlist_leads.id"), index=True)
    ipo_id: Mapped[int] = mapped_column(ForeignKey("ipos.id"), index=True)
    score_snapshot_id: Mapped[int] = mapped_column(ForeignKey("score_snapshots.id"), index=True)
    status: Mapped[str] = mapped_column(String(30), default="sent")
    error: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
